Feat (#1): Create Article component and integrate ReadMoreButton
SAMAHAN-Systems-Development/samahan-palaro-2024 pull request #9
Opened 2024-10-27 11:08 UTC by hamllock

resolves #1 

## Changes
- Created a new reusable Article component based on the Figma design
- Implemented dynamic styling using class-variance-authority (cva) for consistent theming
- Adjusted the ReadMoreButton component to synchronize border and button colors
- Added responsiveness to ReadMoreButton

## Props Interface
```typescript
interface ArticleProps {
  imageUrl: string;
  title: string;
  content: string;
  borderColor: 'blue' | 'green' | 'pink' | 'white';
  headerColor: 'blue' | 'green' | 'pink' | 'white';
  textColor: 'blue' | 'green' | 'pink' | 'white';
  buttonTextColor: 'blue' | 'green' | 'pink' | 'white';
}
```

## Screenshots
![image](https://github.com/user-attachments/assets/cf465a9d-14e1-4487-a28f-60fd4840178e)

2024-10-27 16:00 UTC, mary3l commented on src/components/ui/Article.tsx
> +          src={imageUrl}
change this line to be src={`/images/${imageUrl}`}, it enables you to create dynamic image paths easily

2024-10-27 16:15 UTC, shunindesuuu requested changes

2024-10-27 16:15 UTC, shunindesuuu commented on src/components/ui/Article.tsx
> +        style={{ aspectRatio: '4 / 3' }}
change this to tailwind

2024-10-27 16:15 UTC, shunindesuuu commented on src/components/ui/Article.tsx
> +          style={{ objectFit: 'cover' }}
this one as well

2024-10-29 00:15 UTC, mary3l approved these changes

2024-10-30 13:39 UTC, shunindesuuu approved these changes

2024-10-30 13:39 UTC, shunindesuuu commented on src/components/ui/ReadMoreButton.tsx
>        </span>
have you tried talking to john kyle about the changes here? if not, kindly pm nalang as to why it is changed to this and that

2024-10-30 13:39 UTC, shunindesuuu commented on src/components/ui/ReadMoreButton.tsx
>        </span>
its okay to refactor codes of other people but its important to communicate with each other to avoid confusion, and as much as possible, use a separate branch in order to keep things clean especially if there are multiple changes

2024-11-02 10:57 UTC, merged